version: '3.8'
services:
  
  api:
    container_name: advertisements_board-api
    build:
      context: .
      dockerfile: src/AdvertisementsBoard/Hosts/AdvertisementsBoard.Hosts.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5259
      - ConnectionStrings__PostgresDb=Server=${POSTGRES_SERVER};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Port=${POSTGRES_PORT}
    ports:
      - "5259:5259"
    networks:
      - advertisements_board-network
    depends_on:
      - migrator
      - database
    volumes:
      - ./wwwroot:/app/wwwroot
    command: [ "./wait-for-it.sh", "database:5432", "--", "dotnet", "AdvertisementsBoard.Hosts.Api.dll" ]
  
  migrator:
    container_name: advertisements_board-migrator
    build:
      context: .
      dockerfile: src/AdvertisementsBoard/Hosts/AdvertisementsBoard.Hosts.Migrator/Dockerfile
    ports:
      - "5230:5230"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__PostgresDb=Server=${POSTGRES_SERVER};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Port=${POSTGRES_PORT}
    networks:
      - advertisements_board-network
    depends_on:
      - database
    command: [ "./wait-for-it.sh", "database:5432", "--", "dotnet", "AdvertisementsBoard.Hosts.Migrator.dll" ]
  
  database:
    container_name: advertisements_board-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - advertisements_board-data:/var/lib/postgresql/data/
    networks:
      - advertisements_board-network

networks:
  advertisements_board-network:

volumes:
  advertisements_board-data: