version: '3.7'
services:
  
  api:
    container_name: advertisementsboard-api
    build:
      context: .
      dockerfile: src/AdvertisementsBoard/Hosts/AdvertisementsBoard.Hosts.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5259
      - ConnectionStrings__PostgresAdvertisementsBoardDb=Host=database;Database=AdvertisementsBoardDb;Username=postgres;Password=password;Port=5432
    ports:
      - "5259:5259"
    depends_on:
      - migrator
    networks:
      - advertisementsboard-network
  
  migrator:
    container_name: advertisementsboard-migrator
    build:
      context: .
      dockerfile: src/AdvertisementsBoard/Hosts/AdvertisementsBoard.Hosts.Migrator/Dockerfile
    ports:
      - "5230:5230"
    environment:
      - ConnectionStrings__PostgresAdvertisementsBoardDb=Host=database;Database=AdvertisementsBoardDb;Username=postgres;Password=password;Port=5432
    depends_on:
      - database
    networks:
      - advertisementsboard-network
  
  database:
    container_name: advertisementsboard-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=AdvertisementsBoardDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - advertisementsboard-network

networks:
  advertisementsboard-network:

volumes:
  postgres_data: