version: '3.7'
services:
  
  api:
    container_name: advertisementsboard-api
    build:
      context: .
      dockerfile: src/AdvertisementsBoard/Hosts/AdvertisementsBoard.Hosts.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5259
      - ConnectionStrings__PostqresDb=Server=postgres;Database=AdvertisementsBoard;Username=postgres;Password=password;Port=5432
    ports:
      - "5259:5259"
    depends_on:
      - postgres
    networks:
      - advertisementsboard-network
  
  postgres:
    container_name: advertisementsboard-postqres
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_DB=AdvertisementsBoard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - advertisementsboard-network

networks:
  advertisementsboard-network:

volumes:
  postgres_data: